@startuml

class Project {
- link
- Tag
}

enum Environment

Project "1" o-- "0..*" Tag : dependentTo
Tag "1" -- "0..*" Environment : deployedEnvironments
Tag "1" -- "0..*" Tag : dependentTags
Tag "1" -- "0..*" Tag : dependentOnMeTags





@enduml